---
title: "PAM analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(IPAM2R)   # devtools::install_github(repo = "jrcunning/IPAM2R")
library(lme4)
library(lsmeans)
library(tidyverse)
library(readxl)

theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA)#,
      #axis.text.x = element_text(angle=45, hjust=1, vjust = 1)
    )
}
```

```{r}
# Define function to quantify variance due to fixed and random effects
# Based on code from Quigley et al.: https://datadryad.org/stash/dataset/doi:10.5061/dryad.8b5g6 
varquant <- function(mod) {
  X.var<- var(as.vector(lme4::fixef(mod) %*% t(mod@pp$X)))
  ## Extract the variance components for the random effects (not including the residuals)
  Z.var <- sum(
    sapply(
      VarCorr(mod)[!sapply(unique(unlist(strsplit(names(ranef(mod)),":|/"))), function(l)
        length(unique(mod@frame[,l])) == nrow(mod@frame))],
      function(Sigma) {
        X <- model.matrix(mod)
        Z <- X[,rownames(Sigma)]
        sum(diag(Z %*% Sigma %*% t(Z)))/nrow(X) } ) )
  ## Extract the variance componts for the residuals
  R.var <- attr(lme4::VarCorr(mod), "sc")^2
  ## The marginal R2 (proportion of variance due to fixed effects)
  R2.marginal <- X.var/(X.var+Z.var+R.var)
  # 16 % of variance due to fixed effects: no fixed effects
  ## The proportion of variance due to random effects
  R2.random <- Z.var/(X.var+Z.var+R.var)
  return(list(R2.marginal, R2.random))
}

```

```{r}
# Import sample metadata
sdat <- read_xlsx("data/sample_metadata.xlsx") %>%
  mutate(sample = paste0(species, colony, ".", core),
         sym = if_else(trt1 == "c", "C", "D"),     # recode treatment names
         trt = if_else(trt2 == "h", "heat", "ctrl"),
         symtrt = interaction(sym, trt),
         colony = factor(colony)) %>%
  mutate_if(is.character, as.factor) %>%
  arrange(sample) %>%                              # order by sample name
  column_to_rownames(var = "sample")               # set sample name to rownames
```

```{r}
pam <- import_ipam("data/PAM")

# add treatment info
pam <- pam %>% 
  separate(ID, into = c("colony", "core"))

pam <- right_join(sdat, pam)
```

```{r}
ggplot(pam, aes(x = symtrt, y = Y)) +
  geom_boxplot() + 
  geom_point(aes(color = tank))
```

```{r}
pam <- filter(pam, colony %in% c(20, 22, 26)) %>%
  drop_na()

# remove core that didn't shuffle
pam <- filter(pam, !(colony == 22 & core == 12))


mod <- lmer(Y ~ sym * trt + (1|colony), data = pam)
# Variance due to random effects (genet)
varquant(mod)[[2]]

lsm <- lsmeans(mod, specs = c("trt", "sym"))
summary(lsm)

rbind(pairs(lsm, by = "sym"), adjust = "none")
# No change from ctrl to heat in either sym

contrast(lsm, interaction = "pairwise", by = "trt")
#  Change from ctrl to heat not diff by sym


pamfig <- tibble(summary(lsm)) %>%
  #mutate(trt = recode(trt, ctrl = "Control", heat = "Heated")) %>%
  ggplot(aes(x = trt, y = lsmean, group = sym, shape = sym)) +
  #geom_point(data = pam, position = position_dodge(width = 0.2), aes(y = Y, color = colony, fill = colony)) +
  geom_errorbar(aes(ymin = lsmean - SE, ymax = lsmean + SE),
                position = position_dodge(width = 0.2), lwd = 0.15, width = 0.25) +
  geom_line(position = position_dodge(width = 0.2), lwd = 0.15) +
  geom_point(position = position_dodge(width = 0.2), size = 3, fill = "white") +
    scale_shape_manual(values = c(21, 24)) +
  labs(y = expression(italic("F"[v]*" / F"[m])), x = "") +
  theme_custom() +
  theme(legend.position = c(0.8, 0.9), legend.title = element_blank())

pamfig

save(pamfig, file = "output/pamfig.RData")

data.frame(summary(lsm)) %>%
  select(sym, trt, lsmean) %>%
  spread(trt, lsmean) %>%
  mutate(diff = -(1 - (heat / ctrl)))
```

